on:
  push:
    branches: [ main ]

name: deploy website on push

jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2 

    - name: Rsync Deployments Action
      uses: Burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /var/www/html/CI.CD
        remote_host: 34.41.222.115
        remote_user: testuser
        remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
